- platform: mqtt_room
  name: "Fitbit BLE"
  device_id: "known:c99ef3cfc137"
  state_topic: "espresense/devices/known:c99ef3cfc137"
  timeout: 5
  away_timeout: 120
- platform: mqtt_room
  name: "OnePlus Enrique BLE"
  device_id: "iBeacon:8237a89a-b611-4a87-b698-e5750e922ffe-1-1"
  state_topic: "espresense/devices/iBeacon:8237a89a-b611-4a87-b698-e5750e922ffe-1-1"
  timeout: 5
  away_timeout: 120
  
- platform: template
  sensors:
    shopping_list_aguacates:
      friendly_name: "Aguacates"
      value_template: >
        {% set product = "Aguacates" %}
        {% set products = (state_attr('sensor.shopping_list_items_to_buy','list') or '').split(',') %}
        {%- set items = products | select('equalto', product) | list | length | string -%}
        {{ items | int }}
      entity_picture_template: "https://cdn-icons-png.flaticon.com/256/2771/2771201.png"
      attribute_templates:
        category: "Fruta" 
        store: "Carrefour" 
        total_cost: >
          {{ (2.54 | float) * (states('sensor.shopping_list_aguacates') | float) }}
        units: "Aguacates"
        featured: "Favoritos"

- platform: template
  sensors:
    shopping_list_yogures:
      friendly_name: "Yogures"
      value_template: >
        {% set product = "Yogures" %}
        {% set products = (state_attr('sensor.shopping_list_items_to_buy','list') or '').split(',') %}
        {%- set items = products | select('equalto', product) | list | length | string -%}
        {{ items | int }}
      entity_picture_template: "https://cdn-icons-png.flaticon.com/128/1047/1047469.png"
      attribute_templates:
        category: "Lácteos" 
        store: "Lidl" 
        total_cost: >
          {{ (2.54 | float) * (states('sensor.shopping_list_yogures') | float) }}
        units: "packs"
        featured: "Favoritos"

- platform: template
  sensors:
    shopping_list_pienso_de_gato:
      friendly_name: "Pienso de gato"
      value_template: >
        {% set product = "Pienso de gato" %}
        {% set products = (state_attr('sensor.shopping_list_items_to_buy','list') or '').split(',') %}
        {%- set items = products | select('equalto', product) | list | length | string -%}
        {{ items | int }}
      entity_picture_template: "https://cdn-icons-png.flaticon.com/128/2809/2809799.png"
      attribute_templates:
        category: "Animales" 
        store: "Kiwoko" 
        total_cost: >
          {{ (2.54 | float) * (states('sensor.shopping_list_pienso_de_gato') | float) }}
        units: "kg"
        featured: "Favoritos"

- platform: template
  sensors:
    shopping_list_comida_humeda_de_gato:
      friendly_name: "Comida húmeda de gato"
      value_template: >
        {% set product = "Comida húmeda de gato" %}
        {% set products = (state_attr('sensor.shopping_list_items_to_buy','list') or '').split(',') %}
        {%- set items = products | select('equalto', product) | list | length | string -%}
        {{ items | int }}
      entity_picture_template: "https://cdn-icons-png.flaticon.com/128/8334/8334182.png"
      attribute_templates:
        category: "Animales" 
        store: "Kiwoko" 
        total_cost: >
          {{ (2.54 | float) * (states('sensor.shopping_list_comida_humeda_de_gato') | float) }}
        units: "latas"
        featured: "Favoritos"

- platform: template
  sensors:
    shopping_list_curry:
      friendly_name: "Curry"
      value_template: >
        {% set product = "Curry" %}
        {% set products = (state_attr('sensor.shopping_list_items_to_buy','list') or '').split(',') %}
        {%- set items = products | select('equalto', product) | list | length | string -%}
        {{ items | int }}
      entity_picture_template: "https://cdn-icons-png.flaticon.com/128/9667/9667321.png"
      attribute_templates:
        category: "Especias" 
        store: "Lidl"
        total_cost: >
          {{ (2.54 | float) * (states('sensor.shopping_list_curry') | float) }}
        units: "botes"
        featured: "Favoritos"

- platform: template
  sensors:
    shopping_list_garam_masala:
      friendly_name: "Garam Masala"
      value_template: >
        {% set product = "Garam Masala" %}
        {% set products = (state_attr('sensor.shopping_list_items_to_buy','list') or '').split(',') %}
        {%- set items = products | select('equalto', product) | list | length | string -%}
        {{ items | int }}
      entity_picture_template: "https://cdn-icons-png.flaticon.com/128/1704/1704104.png"
      attribute_templates:
        category: "Especias" 
        store: "Lidl"
        total_cost: >
          {{ (2.54 | float) * (states('sensor.shopping_list_garam_masala') | float) }}
        units: "botes"
        featured: "Favoritos"

- platform: template
  sensors:
    shopping_list_pastillas_de_lavavajillas:
      friendly_name: "Pastillas de lavavajillas"
      value_template: >
        {% set product = "Pastillas de lavavajillas" %}
        {% set products = (state_attr('sensor.shopping_list_items_to_buy','list') or '').split(',') %}
        {%- set items = products | select('equalto', product) | list | length | string -%}
        {{ items | int }}
      entity_picture_template: "https://cdn-icons-png.flaticon.com/128/3629/3629638.png"
      attribute_templates:
        category: "Limpieza" 
        store: "Carrefour"
        total_cost: >
          {{ (2.54 | float) * (states('sensor.shopping_list_pastillas_de_lavavajillas') | float) }}
        units: "cajas"
        featured: "Favoritos"


- platform: template
  sensors:
    shopping_list_sandia:
      friendly_name: "Sandía"
      value_template: >
        {% set product = "Sandía" %}
        {% set products = (state_attr('sensor.shopping_list_items_to_buy','list') or '').split(',') %}
        {%- set items = products | select('equalto', product) | list | length | string -%}
        {{ items | int }}
      entity_picture_template: "https://cdn-icons-png.flaticon.com/256/883/883518.png"
      attribute_templates:
        category: "Fruta" 
        store: "Carrefour" 
        total_cost: >
          {{ (7.75 | float) * (states('sensor.shopping_list_sandia') | float) }}
        units: "Sandías"
        featured: >
          {% if 10 > now().month > 4 %}Temporada
          {% else %}false
          {% endif %} 
